### PR TITLE
Basic dataset pipelines

### PR DESCRIPTION
**Pull request by cloneofsimo**
* Basic stuff : Preprocessor that handles SR, BLIP for autocaption.

Further tricks are planned to go to other repo. Might as well remove these in the future as well, but I'll have these for quick CLI sake

- [x] SR with SwinIR
- [x] BLIP autocaption
- [x] CLIPSeg
- [x] Face Detection
- [x] Support Mask in dataset
- [x] Magic Saving CLI

### CODE REVIEW

**Comment by cloneofsimo** [comment]
image

Simple CLI will now take any directory to create BLIP captioned + SwinIR upscaled + CLIPSeged mask.

**Comment by cloneofsimo** [comment]
Example output : 

image

**Comment by cloneofsimo** [comment]
Usage : 

`lora_ppim ./data/data_cat ./data/data_catpp, --target_prompts="cat"`

**Comment by cloneofsimo** [comment]
By we do you mean stability AI? BTW I've actually developed masking quite a long time ago haha #96

**Comment by Dango233** [comment]
I mean you and me lol. I was exploring the data pipeline for fine-tuning last weekend.

And then I saw your PR lol

**Comment by cloneofsimo** [comment]
Oh yes, lots of room for improvement here. Would gladly accept any PRs 🤗

**Pull request merged**
