### PR TITLE
image transforms

### PR DESCRIPTION
**Pull request by ethansmith2000**
making a fork for my own usage, but thought i'd give a pr as well. thank you for your work!

### CODE REVIEW

**Comment by brian6091** [comment]
Great, looks a lot cleaner! One issue though (which applies in general, not just to your PR) is that if both resize and center_crop are false, you will potentially give the images at different resolutions. Perhaps useful to include a check to force a resize at the end of the pipeline before converting to a tensor? This is useful if you feed the training script images with varying sizes.

I've done this here:
https://github.com/brian6091/Dreambooth/blob/mix/src/datasets.py#L112-132

**Comment by ethansmith2000** [comment]
good point! also noticed there isn't an option for caching latents, I'd be happy to make a pr for that as well if that's something that would be useful

**Comment by brian6091** [comment]
There is an issue for caching latents: https://github.com/cloneofsimo/lora/issues/62

One point is that if you are relying on transformations to augment your data, like color jitter, you caching latents won't help you since you need to run the transformations on each batch.

Maybe you could chime in there. My general feeling is to keep the training scripts in the LoRA repo as simple as possible so that others can easily see what they need to do to adapt their own scripts. But if caching latents saves enough memory to let more people train with lower GPU requirements, then it may be worth it.

**Comment by ethansmith2000** [comment]
ah didn't think of that. good reason to have it optional. 
there probably isn't a reliable way to jitter colors of the latents, but also maybe could do the linear decode trick, apply, and turn it back

**Comment by brian6091** [comment]
Yeah, you could augment in latent space, but I'm not sure anyone knows what that means!

**Comment by cloneofsimo** [comment]
Thanks!

**Pull request merged**
